# App: SQL Generation Agent
# Package: docker
# File: docker-compose.yml
# Version: 0.1.0
# Turns: 1
# Author: gpt-5-codex
# Date: 2025-10-22T20:17:49Z
# Exports: MySQL development service definition
# Description: Defines the MySQL service used for local CustomerProfile domain development and testing.

services:
  mysql-db:
    build:
      context: ./docker/mysql
    container_name: customer-profile-mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    env_file:
      - .env.mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/migrations:/docker-entrypoint-initdb.d/migrations:ro
      - ./db/scripts:/docker-entrypoint-initdb.d/scripts:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    profiles:
      - mysql

volumes:
  mysql-data:
    driver: local
